title: "latentspace."
title_tab: "latentspace"
author: "pch"
description: "<b class=\"site-description\">parkcheolhee-lab</b>"
permalink: /:title/
lang: "en"
excerpt_separator: <!--break-->
date_format: "%B %d, %Y"

google_site_verification: "GKJEYyW0dEIgdiKJcLRyWyeKoYYIW3YwSmsZGfbeEHU"

# Layout

show_excerpts: false        # show article excerpts on the home page
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "testbed", file: "testbed.html"}
  - {title: "notebook", file: "notebook.html"}
  # - {title: "three", file: "threebed.html"}
  # - {title: "r!　", file: "retrospection.html"}
  # - {title: "　", file: "retrospection.html"}

# fontawesome.com/icons
external:  
  # - {title: Mail, icon: envelope, url: "mailto:park112368@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/PARKCHEOLHEE-lab"}
  # - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/cheolhee-park-94577b228/"}
  - {title: cv, icon: id-badge, url: "cv.pdf"}
  # - {title: Issuu, icon: book, url: "https://issuu.com/brighthope03"}
  - {title: p-arc, icon: codepen, url: "portfolio-architectural.pdf"}
  # - {title: resume, icon: address-book, url: "s.pdf"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

utterances:
  repo: "PARKCHEOLHEE-lab/PARKCHEOLHEE-lab.github.io"

highlightjs:
  css: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/stackoverflow-light.min.css"
  js: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"

plugins:
 - jekyll-feed
